auto: true

#markdown: rdiscount
highlighter: 'pygments'
#paginate: 8
permalink: /:title

title: Vakin - 在路上
url: http://vakinge.github.io
feed: /atom.xml
author_info: <a href="http://vakinge.github.io/">Vakin</a>
